# golangci-lint minimal configuration for authentication platform

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic

issues:
  new: false
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m