// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

//go:generate templ generate
func LoginContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"max-w-md mx-auto\" role=\"main\"><section aria-labelledby=\"login-title\"><div class=\"glass-card rounded-2xl shadow-2xl p-8\"><header class=\"text-center mb-8\"><h1 id=\"login-title\" class=\"text-3xl font-bold text-white mb-2\">Welcome Back</h1><p class=\"text-gray-300\">Sign in to your account using secure OAuth providers.</p></header><div class=\"space-y-4\" aria-label=\"Login options\"><a href=\"/auth/google\" class=\"block w-full bg-red-600 hover:bg-red-500 text-white font-semibold py-3 px-6 rounded-xl text-center transition-all duration-300 transform hover:scale-105\">Continue with Google</a> <a href=\"/auth/github\" class=\"block w-full bg-gray-700 hover:bg-gray-600 text-white font-semibold py-3 px-6 rounded-xl text-center transition-all duration-300 transform hover:scale-105\">Continue with GitHub</a></div><footer class=\"mt-6 text-center\"><a href=\"/\" class=\"text-cyan-400 hover:text-cyan-300 text-sm transition-colors duration-200\">← Back to Home</a></footer></div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
