// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.countUsersCreatedThisWeekStmt, err = db.PrepareContext(ctx, countUsersCreatedThisWeek); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersCreatedThisWeek: %w", err)
	}
	if q.countUsersCreatedTodayStmt, err = db.PrepareContext(ctx, countUsersCreatedToday); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersCreatedToday: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getAdminUsersStmt, err = db.PrepareContext(ctx, getAdminUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminUsers: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getRecentUsersStmt, err = db.PrepareContext(ctx, getRecentUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentUsers: %w", err)
	}
	if q.getUserByAuthIDStmt, err = db.PrepareContext(ctx, getUserByAuthID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByAuthID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserAdminStatusStmt, err = db.PrepareContext(ctx, updateUserAdminStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserAdminStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.countUsersCreatedThisWeekStmt != nil {
		if cerr := q.countUsersCreatedThisWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersCreatedThisWeekStmt: %w", cerr)
		}
	}
	if q.countUsersCreatedTodayStmt != nil {
		if cerr := q.countUsersCreatedTodayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersCreatedTodayStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getAdminUsersStmt != nil {
		if cerr := q.getAdminUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminUsersStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getRecentUsersStmt != nil {
		if cerr := q.getRecentUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentUsersStmt: %w", cerr)
		}
	}
	if q.getUserByAuthIDStmt != nil {
		if cerr := q.getUserByAuthIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByAuthIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserAdminStatusStmt != nil {
		if cerr := q.updateUserAdminStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserAdminStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	countUsersStmt                *sql.Stmt
	countUsersCreatedThisWeekStmt *sql.Stmt
	countUsersCreatedTodayStmt    *sql.Stmt
	createUserStmt                *sql.Stmt
	getAdminUsersStmt             *sql.Stmt
	getAllUsersStmt               *sql.Stmt
	getRecentUsersStmt            *sql.Stmt
	getUserByAuthIDStmt           *sql.Stmt
	getUserByEmailStmt            *sql.Stmt
	getUserByIDStmt               *sql.Stmt
	updateUserStmt                *sql.Stmt
	updateUserAdminStatusStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		countUsersStmt:                q.countUsersStmt,
		countUsersCreatedThisWeekStmt: q.countUsersCreatedThisWeekStmt,
		countUsersCreatedTodayStmt:    q.countUsersCreatedTodayStmt,
		createUserStmt:                q.createUserStmt,
		getAdminUsersStmt:             q.getAdminUsersStmt,
		getAllUsersStmt:               q.getAllUsersStmt,
		getRecentUsersStmt:            q.getRecentUsersStmt,
		getUserByAuthIDStmt:           q.getUserByAuthIDStmt,
		getUserByEmailStmt:            q.getUserByEmailStmt,
		getUserByIDStmt:               q.getUserByIDStmt,
		updateUserStmt:                q.updateUserStmt,
		updateUserAdminStatusStmt:     q.updateUserAdminStatusStmt,
	}
}
