// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// This file is a temporary scaffold while refactoring layout/navigation.
// The authoritative layout + navigation currently remain in layout.templ.
// Once the new structure is finalized and verified, we will:
// - Move Layout + UserInfo + Navigation components into this file (layouts)
// - Keep page content in templates/*.templ or templates/pages/
// - Keep shared UI in templates/components/
//
// For now, this file is intentionally empty to avoid duplicate symbol errors.
var _ = templruntime.GeneratedTemplate
