// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Temporary scaffold while organizing templates into:
// - templates/layouts/*.templ     (for layout + navigation shells)
// - templates/pages/*.templ       (for page-level content)
// - templates/components/*.templ  (for shared UI components)
//
// This file intentionally contains no imports or templ definitions so it
// does not conflict with existing generated code. Safe to delete once the
// new structure is fully in place.
var _ = templruntime.GeneratedTemplate
