// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// NOTE: This file intentionally only exists as an extension point.
// The actual navigation components live in layout.templ so that
// Layout + Navigation remain co-located and easy to understand
// for anyone using this starter.
//
// If you want to customize or extract navigation per-project,
// you can move NavigationLoggedIn / NavigationLoggedOut from
// layout.templ into this file and update handlers accordingly.
//
// Kept minimal on purpose to avoid conflicting definitions.
var _ = templruntime.GeneratedTemplate
