// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// NOTE:
// This file is an extension point for per-project navigation components.
// It is intentionally empty so it does not conflict with the default
// navigation defined in layout.templ.
//
// When you customize this starter for a new project, you can:
// - Define templ NavigationLoggedIn(...)
// - Define templ NavigationLoggedOut(...)
// - Define any other nav variants here
// and update handlers to use them.
var _ = templruntime.GeneratedTemplate
